type AccountSnapshotLP @entity {
  id: ID!
  lastUpdatedAt: BigInt!
  lastShare: BigInt!
  lastCumulativeRate: BigInt!
  lastCummulativeRatePenPie: BigInt!
  lastCummulativeRateEQB: BigInt!
}

type RateSnapshotLP @entity {
  id: ID!
  lastUpdatedAt: BigInt!
  cummulativeRate: BigInt!
  cummulativeRatePenPie: BigInt!
  cummulativeRateEQB: BigInt!
}

type AccountSnapshot @entity {
  id: ID!
  lastUpdatedAt: BigInt!
  lastImpliedHolding: String!
  lastBalance: String!
  lastCumulativeRate: String!
  lastCummulativeRatePenPie: String!
  lastCummulativeRateEQB: String!
}
