type AccountSnapshotLP @entity {
  id: ID!
  lastUpdatedAt: BigInt!
  lastShare: BigInt!
  lastCumulativeRate: BigInt!
}

type RateSnapshotLP @entity {
  id: ID!
  lastUpdatedAt: BigInt!
  cummulativeRate: BigInt!
}

type AccountSnapshot @entity {
  id: ID!
  lastUpdatedAt: BigInt!
  lastImpliedHolding: String!
  lastBalance: String!
  lastCumulativeRate: String!
  lastCummulativeRatePenPie: String!
  lastCummulativeRateEQB: String!
}

type RateSnapshot @entity {
  id: ID!
  lastUpdatedAt: BigInt!
  cummulativeRate: String!
  cummulativeRatePenPie: String!
  cummulativeRateEQB: String!
}