
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'






@Entity("AccountSnapshot")
export class AccountSnapshot  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("BigInt")
	lastUpdatedAt: BigInt

	@Required
	@Column("String")
	lastImpliedHolding: String

	@Required
	@Column("String")
	lastBalance: String

	@Required
	@Column("String")
	lastCumulativeRate: String

	@Required
	@Column("String")
	lastCummulativeRatePenPie: String

	@Required
	@Column("String")
	lastCummulativeRateEQB: String

  constructor(data: Partial<AccountSnapshot>) {}

}

@Entity("RateSnapshot")
export class RateSnapshot  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("BigInt")
	lastUpdatedAt: BigInt

	@Required
	@Column("String")
	cummulativeRate: String

	@Required
	@Column("String")
	cummulativeRatePenPie: String

	@Required
	@Column("String")
	cummulativeRateEQB: String

  constructor(data: Partial<RateSnapshot>) {}

}


const source = `type AccountSnapshot @entity {
  id: ID!
  lastUpdatedAt: BigInt!
  lastImpliedHolding: String!
  lastBalance: String!
  lastCumulativeRate: String!
  lastCummulativeRatePenPie: String!
  lastCummulativeRateEQB: String!
}

type RateSnapshot @entity {
  id: ID!
  lastUpdatedAt: BigInt!
  cummulativeRate: String!
  cummulativeRatePenPie: String!
  cummulativeRateEQB: String!
}`
DatabaseSchema.register({
  source,
  entities: {
    "AccountSnapshot": AccountSnapshot,
		"RateSnapshot": RateSnapshot
  }
})
