
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'






@Entity("AccountSnapshotLP")
export class AccountSnapshotLP  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("BigInt")
	lastUpdatedAt: BigInt

	@Required
	@Column("BigInt")
	lastShare: BigInt

	@Required
	@Column("BigInt")
	lastCumulativeRate: BigInt

	@Required
	@Column("BigInt")
	lastCummulativeRatePenPie: BigInt

	@Required
	@Column("BigInt")
	lastCummulativeRateEQB: BigInt

  constructor(data: Partial<AccountSnapshotLP>) {}

}

@Entity("RateSnapshotLP")
export class RateSnapshotLP  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("BigInt")
	lastUpdatedAt: BigInt

	@Required
	@Column("BigInt")
	cummulativeRate: BigInt

	@Required
	@Column("BigInt")
	cummulativeRatePenPie: BigInt

	@Required
	@Column("BigInt")
	cummulativeRateEQB: BigInt

  constructor(data: Partial<RateSnapshotLP>) {}

}

@Entity("AccountSnapshot")
export class AccountSnapshot  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("BigInt")
	lastUpdatedAt: BigInt

	@Required
	@Column("String")
	lastImpliedHolding: String

	@Required
	@Column("String")
	lastBalance: String

	@Required
	@Column("String")
	lastCumulativeRate: String

	@Required
	@Column("String")
	lastCummulativeRatePenPie: String

	@Required
	@Column("String")
	lastCummulativeRateEQB: String

  constructor(data: Partial<AccountSnapshot>) {}

}


const source = `type AccountSnapshotLP @entity {
  id: ID!
  lastUpdatedAt: BigInt!
  lastShare: BigInt!
  lastCumulativeRate: BigInt!
  lastCummulativeRatePenPie: BigInt!
  lastCummulativeRateEQB: BigInt!
}

type RateSnapshotLP @entity {
  id: ID!
  lastUpdatedAt: BigInt!
  cummulativeRate: BigInt!
  cummulativeRatePenPie: BigInt!
  cummulativeRateEQB: BigInt!
}

type AccountSnapshot @entity {
  id: ID!
  lastUpdatedAt: BigInt!
  lastImpliedHolding: String!
  lastBalance: String!
  lastCumulativeRate: String!
  lastCummulativeRatePenPie: String!
  lastCummulativeRateEQB: String!
}
`
DatabaseSchema.register({
  source,
  entities: {
    "AccountSnapshotLP": AccountSnapshotLP,
		"RateSnapshotLP": RateSnapshotLP,
		"AccountSnapshot": AccountSnapshot
  }
})
