
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'

@Entity("AccountSnapshot")
export class AccountSnapshot  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("BigInt")
	lastUpdatedAt: BigInt

	@Required
	@Column("String")
	lastImpliedHolding: String

	@Required
	@Column("String")
	lastShare: String

	@Required
	@Column("String")
	lastCumulativeRate: String

  constructor(data: Partial<AccountSnapshot>) {}

}

@Entity("RateSnapshot")
export class RateSnapshot  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("BigInt")
	lastUpdatedAt: BigInt

	@Required
	@Column("String")
	cummulativeRate: String

  constructor(data: Partial<RateSnapshot>) {}

}

const source = `type AccountSnapshot @entity {
  id: ID!
  lastUpdatedAt: BigInt!
  lastImpliedHolding: String!
  lastShare	: String!
  lastCumulativeRate: String!
}

type RateSnapshot @entity {
  id: ID!
  lastUpdatedAt: BigInt!
  cummulativeRate: String!
}`
DatabaseSchema.register({
  source,
  entities: {
    "AccountSnapshot": AccountSnapshot,
		"RateSnapshot": RateSnapshot
  }
})
